# Site settings
title: JM'sWhat's
imageurl: "img/bg1.jpg"
email: ema@apache.org
copyright_name:
description: "A place to put my study log and comment"
baseurl: ""
url: "http://jimma.github.io"
twitter_username: jimma
github_username:  jimma
facebook_username: jimma
email_username:  Jim Ma

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
#highlighter: roug
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: java
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
